version: '3'
services:
  web:
    build: .
    entrypoint: /app/docker-entrypoint.sh
    volumes:
      - './workbench:/app/workbench'
    environment:
      PORT: 8080
      PATH: '/app/.heroku/php/bin:/app/.heroku/php/sbin:$PATH'
    ports:
      - '8080:8080'