name: Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  phpunit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.4"
          extensions: redis, soap, sodium, curl
          coverage: none

      - uses: ramsey/composer-install@v3

      - run: vendor/bin/phpunit
